name: stacked_cli
description: The official dev tools for the Stacked Framework
version: 1.15.4
homepage: https://stacked.filledstacks.com/docs/stacked-cli
repository: https://github.com/FilledStacks/stacked/tree/master/packages/stacked_cli

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  args: ^2.4.2
  freezed_annotation: ^2.1.0
  get_it: 9.2.0
  mockito: ^5.4.3
  mustache_template: ^2.0.0
  path: ^1.8.1
  pubspec_yaml: ^3.1.0
  recase: ^4.0.0
  json_annotation: ^4.8.1
  ansicolor: ^2.0.2
  xdg_directories: ^1.0.0
  pub_updater: ^0.5.0
  http: ^1.1.2
  hive: ^2.2.3
  async: ^2.13.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0

  build_runner: ^2.4.7
  freezed: ^2.3.4
  json_serializable: ^6.7.1

executables:
  stacked:
